apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: gcp-store
  namespace: default
spec:
  provider:
    gcpsm:                                  # gcpsm provider
      auth:
        secretRef:
          secretAccessKeySecretRef:
            name: gcp-creds              # secret name containing SA key
            key: creds_json  # key name containing SA key
      projectID: gustavo-is-testing-stuff               # name of Google Cloud project
